# Generated by Django 3.0 on 2019-12-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20191221_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainnews',
            name='img',
            field=models.TextField(default='img'),
            preserve_default=False,
        ),
    ]
